### ISSUE TITLE
Node is either not visible or not an HTMLElement

### ISSUE THREAD

**Issue by mahaoming** [muxiangqiu/puppeteer-fc-starter-kit#1]
请问这个报错和chrome的版本有影响吗
```
const setup = require('./starter-kit/setup');

exports.handler = async (event, context, callback) => {
    const browser = await setup.getBrowser(context);
    exports.run(browser).then(
        (result) => {
            console.log(result);
            callback(null, result);
        }
    ).catch(
        (err) => callback(err)
    );
};

// dom element selectors
const USERNAME_SELECTOR = '#username';
const PASSWORD_SELECTOR = '#password';
const BUTTON_SELECTOR = '#lif > div:nth-child(5) > input';

let username = '1801211923';
let password = 'Pleasetrustme0731';

exports.run = async (browser) => {
    let code = 0;

    const page = await browser.newPage();
    await page.goto('https://its.pku.edu.cn/', {
        waitUntil: 'domcontentloaded',
    });

    await page.waitFor(USERNAME_SELECTOR);
    await page.click(USERNAME_SELECTOR);
    await page.keyboard.type(username);

    await page.waitFor(PASSWORD_SELECTOR);
    await page.click(PASSWORD_SELECTOR);
    await page.keyboard.type(password);


    await page.click(BUTTON_SELECTOR);

    try {
        await page.waitForNavigation({'timeout': 5000});
        await page.screenshot({path: 'src/screenshot/3.png'});
    } catch (err) {
        code = 1;
    }

    // await browser.close();

    let jsonResponse = {
        code: code,
        msg: 'ok',
        data: '',
    };
    return jsonResponse;
};
```

**Comment by mahaoming** [comment]
在本地上运行时正常的，但打包通过fcli上传之后就报错了

**Comment by muxiangqiu** [comment]
" run npm run package, and deploy the package.zip on FC ."，是按照这个方式来打包的吗

**Comment by muxiangqiu** [comment]
报什么错？

**Comment by mahaoming** [comment]
运行这个报这个错误
```json
{
	"errorMessage": "Node is either not visible or not an HTMLElement",
	"errorType": "Error",
	"stackTrace": ["at _clickablePoint (/code/node_modules/puppeteer/lib/ExecutionContext.js:331:13)", "at (<anonymous>)", "at _tickCallback (internal/process/next_tick.js:188:7)", "-- ASYNC --", "at (/code/node_modules/puppeteer/lib/helper.js:144:27)", "at click (/code/node_modules/puppeteer/lib/FrameManager.js:705:18)", "at (<anonymous>)", "at _tickCallback (internal/process/next_tick.js:188:7)", "-- ASYNC --", "at (/code/node_modules/puppeteer/lib/helper.js:144:27)", "at click (/code/node_modules/puppeteer/lib/Page.js:924:29)", "at exports.run (/code/index.js:33:16)", "at (<anonymous>)", "at _tickCallback (internal/process/next_tick.js:188:7)"]
}
```

**Comment by mahaoming** [comment]
如果不使用
```
    await page.waitFor(USERNAME_SELECTOR);
    await page.click(USERNAME_SELECTOR);
    await page.keyboard.type(username);

    await page.waitFor(PASSWORD_SELECTOR);
    await page.click(PASSWORD_SELECTOR);
    await page.keyboard.type(password);


    await page.click(BUTTON_SELECTOR);
```
这一块的话是可以正常返回的
就是这部分是正常的
```
const page = await browser.newPage();
    await page.goto('https://its.pku.edu.cn/', {
        waitUntil: 'domcontentloaded',
    });
```
这会是chrom的版本问题吗

**Comment by mahaoming** [comment]
你好，试了下在本地cnpm install puppeteer 是可以正常运行，如果要构建最新的版的chorme要怎么打包呢
